fragment roundsubmissionParts on Roundsubmission {
  id
  status
  round {
    id
    index
  }
  participant {
    ...userParts
  },
  originalParticipant {
    ...userParts
  }
  song { id }
  fileSeeded {
    id
    filename
    downloadUrl
  }
  fileSubmitted {
    id
    filename
    downloadUrl
  }
}
