fragment roundsubmissionParts on Roundsubmission {
  id
  status
  round { id index }
  participant {
    username
  },
  originalParticipant {
    username
  }
  song { id, index }
  fileSubmitted {
    id
    filename
    downloadUrl
  }
}
