module.exports = [
  { path: '/',
    component: () => import(/* webpackChunkName: "start" */ './components/Start.vue') },
  { path: '/index.php',
    component: () => import(/* webpackChunkName: "start" */ './components/Start.vue') },
  { path: '/events',
    component: () => import(/* webpackChunkName: "events-page" */ './components/EventsPage.vue') },
  { path: '/events/:slug',
    component: () => import(/* webpackChunkName: "event-page" */ './components/EventPage.vue') },
  { path: '/events/:slug/edit',
    component: () => import(/* webpackChunkName: "edit-event" */ './components/EditEvent.vue') },
  { path: '/create-event',
    component: () => import(/* webpackChunkName: "create-event" */ './components/CreateEvent.vue') },
  { path: '/events/:slug',
    component: () => import(/* webpackChunkName: "event" */ './components/Event.vue') },
  { path: '/events/:slug/roundsubmissions',
    component: () => import(/* webpackChunkName: "event" */ './components/RoundsubmissionsList.vue') },
  { path: '/roundsubmissions/:id',
    component: () => import(/* webpackChunkName: "roundsubmission" */ './components/Roundsubmission.vue') },
  { path: '/register',
    component: () => import(/* webpackChunkName: "register" */ './components/RegistrationForm.vue') },
  { path: '/login',
    component: () => import(/* webpackChunkName: "login-form" */ './components/LoginForm.vue') },
  { path: '/forgot-password',
    component: () => import(/* webpackChunkName: "forgot-password-form" */ './components/ForgotPasswordForm.vue') },
  { path: '/users',
    component: () => import(/* webpackChunkName: "users-page" */ './components/UsersPage.vue') },
  { path: '/users/:slug',
    component: () => import(/* webpackChunkName: "user" */ './components/User.vue') },
  { path: '/users/:id/activation/:code',
    component: () => import(/* webpackChunkName: "activate-user" */ './components/ActivateUser.vue') },
  { path: '/disclaimer',
    component: () => import(/* webpackChunkName: "disclaimer" */ './components/Disclaimer.vue') },
  { path: '/privacy-policy',
    component: () => import(/* webpackChunkName: "privacy-policy" */ './components/PrivacyPolicy.vue') },
  { path: '/related-links',
    component: () => import(/* webpackChunkName: "related-links" */ './components/RelatedLinks.vue') },
  { path: "*",
    component: () => import(/* webpackChunkName: "not-found" */ './components/NotFound.vue') }
];
