module.exports = [
  { path: '/',
    component: () => import(/* webpackChunkName: "start" */ './components/Start.vue') },
  { path: '/events',
    component: () => import(/* webpackChunkName: "events-list" */ './components/EventsList.vue') },
  { path: '/events/:slug',
    component: () => import(/* webpackChunkName: "event" */ './components/Event.vue') },
  { path: '/events/:slug/roundsubmissions',
    component: () => import(/* webpackChunkName: "event" */ './components/RoundsubmissionsList.vue') },
  { path: '/roundsubmissions/:id',
    component: () => import(/* webpackChunkName: "roundsubmission" */ './components/Roundsubmission.vue') },
  { path: '/register',
    component: () => import(/* webpackChunkName: "register" */ './components/RegistrationForm.vue') },
  { path: '/login',
    component: () => import(/* webpackChunkName: "login-form" */ './components/LoginForm.vue') },
  { path: '/forgot-password',
    component: () => import(/* webpackChunkName: "forgot-password-form" */ './components/ForgotPasswordForm.vue') },
  { path: '/users',
    component: () => import(/* webpackChunkName: "users-list" */ './components/UsersList.vue') },
  { path: '/users/:slug',
    component: () => import(/* webpackChunkName: "user" */ './components/User.vue') },
  { path: '/disclaimer',
    component: () => import(/* webpackChunkName: "disclaimer" */ './components/Disclaimer.vue') },
  { path: '/privacy-policy',
    component: () => import(/* webpackChunkName: "privacy-policy" */ './components/PrivacyPolicy.vue') },
  { path: '/related-links',
    component: () => import(/* webpackChunkName: "related-links" */ './components/RelatedLinks.vue') },
];
