mutation CreateEvent(
  $name: String!
  $description: String!
  $areChangesVisible: Boolean!
  $isScheduleVisible: Boolean!
  $isPublic: Boolean!
  $captchaResponse: String!
) {
  createEvent(params: {
    name: $name
    description: $description
    areChangesVisible: $areChangesVisible
    isScheduleVisible: $isScheduleVisible
    isPublic: $isPublic
    captchaResponse: $captchaResponse
  }) {
    id
    slug
  }
}
