#import "./fragments/userParts.gql"
#import "./fragments/roundsubmissionParts.gql"

query Events (
  $details: Boolean = false,
  $offset: Int = 0,
  $limit: Int = 500,
  $maxDescription: Int = null,
  $gravatarSize: Int = 40,
  $filters: EventsFilter,
  $sort: EventsSortField = id,
  $descending: Boolean = false
) {
  events(selection: {
    offset: $offset,
    limit: $limit,
    sort: $sort,
    descending: $descending,
    filters: $filters
  }) {
    id
    slug
    name
    status
    description(maxLength: $maxDescription)
    currentRound {
      id
      index
    }
    currentRoundsubmission {
      ...roundsubmissionParts
    }
    numRounds
    numParticipants
    roundsubmissions @include(if: $details) {
      ...roundsubmissionParts
    }
    participants @include(if: $details)  {
      ...userParts
    }
    host {
      ...userParts
    }
    areChangesVisible
    isScheduleVisible
    isParticipant
    isAdministrator
    isPublic
    ... on AdministeredEvent {
      initialFile {
        id
        filename
        sizeHuman
        downloadUrl
      }
      invitedUsers {
        ...userParts
      }
    }
  }
}
