mutation LoginUser($username: String!, $password: String!) {
  loginUser(params: {username: $username, password: $password}) {
    user {
      id
      username
      smallGravatar: gravatar(size: 40)
      bigGravatar: gravatar
    }
    authToken
  }
}
