mutation RegisterUser(
  $email: String!,
  $username: String!,
  $password: String!,
  $firstname: String!,
  $lastname: String!,
  $captchaResponse: String!
) {
  createUser(params: {
    email: $email,
    username: $username,
    password: $password, 
    firstname: $firstname,
    lastname: $lastname,
    captchaResponse: $captchaResponse
  }) {
    code
    message
  }
}
