#import "./fragments/userParts.gql"
#import "./fragments/fileParts.gql"

query Roundsubmissions (
  $offset: Int = 0,
  $limit: Int = 500,
  $sort: RoundsubmissionsSortField = id,
  $descending: Boolean = false,
  $gravatarSize: Int = 40,
  $filters: RoundsubmissionsFilter = {}
) {
  roundsubmissions(selection: {
    offset: $offset,
    limit: $limit,
    sort: $sort,
    descending: $descending,
    filters: $filters
  }) {
    id
    event {
      id
      status
      name
      slug
      isPublic
      isParticipant
      isScheduleVisible
      areChangesVisible
      isAdministrator
    }
    round { id index }
    song { id index }
    status
    participant { ...userParts }
    originalParticipant { ...userParts }
    fileSeeded { ...fileParts }
    fileSubmitted { ...fileParts }
  }
}
