mutation SkipRound(
  $roundsubmissionId: ID!
  $userId: ID = null
) {
  skipRound(params: {
    roundsubmissionId: $roundsubmissionId
    userId: $userId
  }) {
    code
    message
  }
}
