mutation UpdateEvent(
  $id: ID!
  $name: String!
  $description: String!
  $areChangesVisible: Boolean!
  $isScheduleVisible: Boolean!
  $isPublic: Boolean!
) {
  updateEvent(params: {
    id: $id
    name: $name,
    description: $description,
    areChangesVisible: $areChangesVisible
    isScheduleVisible: $isScheduleVisible
    isPublic: $isPublic
  }) {
    code
    message
  }
}
